name: 🤖 HW Support Request
description: Support request for HW maintenance
assignees: "sgiraz,AntonioConsilvio"
title: "[Give a meaningful title but don't enter the robot name here]"

body:
- type: markdown
  attributes:
    value: |
      ⚠
      Verify first that your issue is not [already reported on GitHub][issue search].

      [issue search]: https://github.com/robotology/icub-tech-support/search?q=is%3Aissue&type=issues    
- type: dropdown
  id: robot
  attributes:
    label: Robot Name 🤖
    description: Please enter the name of your robot.
    options:
      - "ergoCub 1.0 S/N:000"
      - "ergoCub 1.1 S/N:001"
      - "ergoCub 1.1 S/N:002"
      - "iCubAberystwyth01 S/N:018"
      - "iCubAnkara01 S/N:12"
      - "iCubBarcelona01 S/N:013"
      - "iCubBielefeld01 S/N:006"
      - "iCubBielefeld03 S/N:019"
      - "iCubChemnitz01 S/N:042"
      - "iCubDarmstadt01 S/N:025"
      - "iCubEdinburgh01 S/N:034"
      - "iCubErzelli01 S/N:032"
      - "iCubErzelli02 S/N:036"
      - "iCubFrankfurt01 S/N:019H"
      - "iCubGenova01 S/N:000"
      - "iCubGenova02 S/N:001"
      - "iCubGenova03 S/N:020"
      - "iCubGenova04 (iRonCub1) S/N:031"
      - "iCubGenova07 S/N:040"
      - "iCubGenova08 S/N:043"
      - "iCubGenova09 (iRonCub3) S/N:000"
      - "iCubGenova10 S/N:046"
      - "iCubGenova11 S/N:050"
      - "iCubGrenoble01 S/N:023"
      - "iCubHamburg01 S/N:027H"
      - "iCubHeidelberg01 S/N:029"
      - "iCubHertfordshire01 S/N:009"
      - "iCubHongKong01 S/N:041"
      - "iCubLausanne01 S/N:005"
      - "iCubLausanne02 S/N:033"
      - "iCubLisboa01 S/N:004"
      - "iCubLondon01 S/N:003"
      - "iCubLugano01 S/N:017"
      - "iCubLyon01 S/N:010"
      - "iCubManchester01 S/N:011"
      - "iCubMoscow01 S/N:038"
      - "iCubMunich01 S/N:008"
      - "iCubNancy01 S/N:021"
      - "iCubNottingham01 S/N:027"
      - "iCubTokyo01 S/N:022"
      - "iCubParis01 S/N:002"
      - "iCubParis02 S/N:024"
      - "iCubPisa01 S/N:037"
      - "iCubPlymouth01 S/N:007"
      - "iCubPrague01 S/N:047"
      - "iCubRome02 S/N:016"
      - "iCubSeoul01 S/N:026"
      - "iCubShanghai01 S/N:049"
      - "iCubSheffield01 S/N:028"
      - "iCubShenzhen01 S/N:039"
      - "iCubSingapore01 S/N:035"
      - "iCubTwente01 S/N:030"
      - "iCubUrbana01 S/N:015"
      - "iCubValparaiso01 S/N:048"
      - "iCubWaterloo01 S/N:044"
      - "iCubZagreb01 S/N:045"
      - "R1 S/N:000"
      - "R1 S/N:001"
      - "R1 S/N:002"
      - "R1 S/N:003"
- type: textarea
  id: description
  attributes:
    label: Request/Failure description
    description: Summarize the request concisely.
  validations:
    required: true
- type: textarea
  attributes:
    label: Detailed context
    description: Provide a more detailed description of the problem.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Please attach here any material you may consider useful (pictures, screenshots, logs, etc.).
- type: textarea
  attributes:
    label: How does it affect you?
    description: Optional field where you can quantify the impact of the issue on your workflow.
