name: 🤖 HW Support Request
description: Support request for HW maintenance
assignees: "sgiraz,AntonioConsilvio"
body:
- type: markdown
  attributes:
    value: |
      ⚠
      Verify first that your issue is not [already reported on GitHub][issue search].

      [issue search]: https://github.com/robotology/icub-tech-support/search?q=is%3Aissue&type=issues    
- type: input
  attributes:
    label: Device name 🤖
    description: Please enter the name of your robot or device. If you are allowed, also assign the corresponding label 🔖
    placeholder: iCub[Town][XY], R1SN[XYZ], IIT[ABCDE]_SN[XYZ]...
  validations:
    required: true
- type: textarea
  attributes:
    label: Request/Failure description
    description: Summarize the request concisely.
  validations:
    required: true
- type: textarea
  attributes:
    label: Detailed context
    description: Provide a more detailed description of the problem.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Please attach here any material you may consider useful (pictures, screenshots, logs, etc.).
- type: textarea
  attributes:
    label: How does it affect you?
    description: Optional field where you can quantify the impact of the issue on your workflow.
